# Teihai70H
# Author: alg
# Board : RP2040Zero

kbd = Keyboard.new

kbd.init_pins(
  [  1,  3,  4,  5,  6, 11, 10,  9,  8,  7 ], # rows
  [ 28, 27, 26, 15, 14, 13, 12 ]              # columns
)

kbd.add_layer :default, %i(
  KC_ESC  KC_1    KC_2    KC_3    KC_4    KC_5    KC_6
  KC_TAB  KC_Q    KC_W    KC_E    KC_R    KC_T    KC_Y
  KC_LCTL KC_A    KC_S    KC_D    KC_F    KC_G    KC_H
  KC_LSFT KC_Z    KC_X    KC_C    KC_V    KC_B    KC_N
  TO_FN   KC_GRV  KC_LGUI KC_LALT KC_INT5 KC_SPC  KC_SPC
  KC_7    KC_8    KC_9    KC_0    KC_MINS KC_EQL  KC_INT3
  KC_U    KC_I    KC_O    KC_P    KC_LBRC KC_RBRC KC_BSPC
  KC_J    KC_K    KC_L    KC_SCLN KC_QUOT KC_BSLS KC_ENT
  KC_M    KC_COMM KC_DOT  KC_SLSH KC_INT1 KC_UP   KC_RSFT
  KC_INT4 KC_INT2 KC_RALT TO_FN   KC_LEFT KC_DOWN KC_RGHT
)
kbd.add_layer :fn, %i(
  KC_TRNS KC_F1   KC_F2   KC_F3   KC_F4   KC_F5   KC_F6
  KC_CAPS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS
  KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_PAST
  KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_PPLS
  KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_TRNS
  KC_F7   KC_F8   KC_F9   KC_F10  KC_F11  KC_F12  KC_INS
  KC_TRNS KC_PSCR KC_SCRL KC_PAUS KC_UP   KC_TRNS KC_DEL
  KC_PSLS KC_HOME KC_PGUP KC_LEFT KC_RGHT KC_TRNS KC_PENT
  KC_PMNS KC_END  KC_PGDN KC_DOWN KC_TRNS KC_RSFT KC_TRNS
  KC_TRNS KC_TRNS KC_TRNS KC_TRNS KC_DEL  KC_RGUI KC_RCTL
)

kbd.define_mode_key :TO_FN, [ :KC_NONE, :fn, 200, 200 ]

kbd.start!
